module.exports = {
  navLinks: [
    { name: 'Home', url: '/' },
    { name: 'Shop', url: '/shop' },
    { name: 'About Us', url: '/about' },
    { name: 'Contact Us', url: '/contact' },
  ],
  categories: [
    {
      name: 'Bedroom',
      items: '15',
      icon: '/images/icons/bed.svg',
      image: '/images/category/category-1.jpg',
      url: '/bedroom',
    },
    {
      name: 'Sofa',
      items: '15',
      icon: '/images/icons/sofa.svg',
      image: '/images/category/category-2.jpg',
      url: '/sofa',
    },
    {
      name: 'Office',
      items: '15',
      icon: '/images/icons/office.svg',
      image: '/images/category/category-3.jpg',
      url: '/office',
    },
    {
      name: 'Outdoor',
      items: '15',
      icon: '/images/icons/terrace.svg',
      image: '/images/category/category-4.jpg',
      url: '/outdoor',
    },
    {
      name: 'Mattress',
      items: '15',
      icon: '/images/icons/bed-2.svg',
      image: '/images/category/category-5.jpg',
      url: '/mattress',
    },
    {
      name: 'Dining',
      items: '15',
      icon: '/images/icons/restaurant.svg',
      image: '/images/category/category-6.jpg',
      url: '/dining',
    },
  ],
  brands: [
    { name: 'Dominik', items: '15' },
    { name: 'Karl', items: '18' },
    { name: 'Maxing', items: '09' },
    { name: 'Ernest', items: '05' },
  ],
  features: [
    {
      title: 'Free shipping',
      subtitle: 'Order over $200',
      icon: '/images/icons/delivery-van.svg',
    },
    {
      title: 'Money returns',
      subtitle: '30 Days money return',
      icon: '/images/icons/money-back.svg',
    },
    {
      title: '24 / 7 Support',
      subtitle: 'Customer support',
      icon: '/images/icons/service-hours.svg',
    },
  ],
  products: [
    {
      title: 'Guyer Chair',
      image: '/images/products/product1.jpg',
      price: '45.00',
      lessPrice: '55.00',
      reviews: [0, 1, 2, 3],
      review: 5,
    },
    {
      title: 'Guyer Chair',
      image: '/images/products/product1.jpg',
      price: '45.00',
      lessPrice: '55.00',
      reviews: [0, 1, 2, 3],
      review: 5,
    },
    {
      title: 'Guyer Chair',
      image: '/images/products/product1.jpg',
      price: '45.00',
      lessPrice: '55.00',
      reviews: [0, 1, 2, 3],
      review: 5,
    },
    {
      title: 'Guyer Chair',
      image: '/images/products/product1.jpg',
      price: '45.00',
      lessPrice: '55.00',
      reviews: [0, 1, 2, 3],
      review: 5,
    },
  ],
};
